apiVersion: v1
kind: Service
metadata:
  name: forecast-api
  labels:
    app: timeseries-forecast
spec:
  type: ClusterIP
  selector:
    app: timeseries-forecast
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
